
import React from 'react';
import { LogoIcon } from '../icons';

interface PdfReportLayoutProps {
  title: string;
  projectName: string;
  reportDate: string;
  generatedBy: string;
  children: React.ReactNode;
}

const PdfReportLayout = React.forwardRef<HTMLDivElement, PdfReportLayoutProps>(({ title, projectName, reportDate, generatedBy, children }, ref) => {
  return (
    // This outer div provides the gray page background for the PDF. html2canvas captures this element.
    <div ref={ref} className="bg-neutral-100 p-8 font-sans" style={{ width: '210mm', minHeight: '297mm', boxSizing: 'border-box' }}>
        {/* This inner div is the white card containing the report content. */}
        <div className="bg-white rounded-xl shadow-lg p-8 relative" style={{ minHeight: '277mm' }}>
            {/* Header */}
            <div className="flex justify-between items-center pb-4 border-b border-neutral-300">
                <div className="flex items-center space-x-3">
                    <LogoIcon className="w-10 h-10 text-primary-600" />
                    {/* FIX: Corrected company name typo from ConstructFI to ConstructFlow. */}
                    <span className="text-2xl font-extrabold text-neutral-800">Construct<span className="text-primary-600">Flow</span></span>
                </div>
                <h1 className="text-2xl font-bold text-neutral-600">{title}</h1>
            </div>

            {/* Metadata */}
            <div className="grid grid-cols-3 gap-4 my-6 text-sm">
                <div>
                    <p className="font-semibold text-neutral-500 uppercase text-xs tracking-wider">Project</p>
                    <p className="text-neutral-800 font-bold">{projectName}</p>
                </div>
                <div>
                    <p className="font-semibold text-neutral-500 uppercase text-xs tracking-wider">Report Date</p>
                    <p className="text-neutral-800 font-bold">{new Date(reportDate).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
                </div>
                <div>
                    <p className="font-semibold text-neutral-500 uppercase text-xs tracking-wider">Generated By</p>
                    <p className="text-neutral-800 font-bold">{generatedBy}</p>
                </div>
            </div>
            
            <div className="w-full h-px bg-neutral-200 my-4"></div>

            {/* Content */}
            <main className="mt-4">
                {children}
            </main>

            {/* Footer */}
            <div className="absolute bottom-8 left-8 right-8 text-xs text-neutral-400 text-center">
                Generated on {new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })} by ConstructFlow
            </div>
        </div>
    </div>
  );
});

export default PdfReportLayout;
